name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build Angular app
        run: |
          cd apps/h-cars-frontend 
          npm install
          npm run build --if-present

      - name: Install dependencies for the backend API
        run: |
          cd apps/h-cars
          npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Angular app to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          action: "upload"
          app_location: "h-cars"

      - name: Deploy backend API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'h-cars'
          slot-name: 'Production' 
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: 'h-cars'  
