name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      - name: Zip artifacts for deployment
        run: |
          cd dist/apps/h-cars-frontend && zip -r h-cars-frontend.zip *

      - name: Upload h-cars-frontend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: h-cars-frontend
          path: h-cars-frontend.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: h-cars-frontend

      - name: Unzip artifact for deployment
        run: unzip -o h-cars-frontend.zip -d dist/apps/h-cars-frontend

      - name: Deploy to static Azure Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "dist/apps/h-cars-frontend"

  deploy-backend-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: h-cars

      - name: Unzip artifact for deployment
        run: unzip -o h-cars-release.zip -d dist/apps/h-cars

      - name: Install dependencies
        working-directory: dist/apps/h-cars
        run: npm ci

      - name: Deploy to Azure App Service for Node.js
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'h-cars'  # Replace with your Azure App Service name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: .

# Add more steps if needed for database migrations, environment setup, etc.
